# Generated by Django 5.0.2 on 2024-02-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('PRC', 'Processing'), ('D', 'Done'), ('C', 'Cancelled'), ('IAC', 'Inactive'), ('PSPN', 'Posponed'), ('WRK', 'Working')], default='P', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('PRC', 'Processing'), ('D', 'Done'), ('C', 'Cancelled'), ('IAC', 'Inactive'), ('PSPN', 'Posponed'), ('WRK', 'Working')], default='P', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task', to='projects.projects')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
